const cuisineTags = [
  { title: 'Mediterranean', category: 'Cuisine' },
  { title: 'Greek', category: 'Cuisine' },
  { title: 'Thai', category: 'Cuisine' },
  { title: 'Korean', category: 'Cuisine' },
  { title: 'Chinese', category: 'Cuisine' },
  { title: 'Italian', category: 'Cuisine' },
  { title: 'Japanese', category: 'Cuisine' },
  { title: 'French', category: 'Cuisine' },
  { title: 'American', category: 'Cuisine' },
  { title: 'Asian', category: 'Cuisine' },
  { title: 'Mexican', category: 'Cuisine' },
  { title: 'Indian', category: 'Cuisine' },
  { title: 'Middle Eastern', category: 'Cuisine' },
  { title: 'British', category: 'Cuisine' },
  { title: 'Canadian', category: 'Cuisine' },
  { title: 'Caribbean', category: 'Cuisine' },
  { title: 'Latin American', category: 'Cuisine' },
  { title: 'Vietnamese', category: 'Cuisine' },
  { title: 'Filipino', category: 'Cuisine' }
];

const foodtypeTags = [
  { title: 'Chicken Wings', category: 'Food Types' },
  { title: 'Noodles', category: 'Food Types' },
  { title: 'Rice', category: 'Food Types' },
  { title: 'Curry', category: 'Food Types' },
  { title: 'Pizza', category: 'Food Types' },
  { title: 'Breakfast', category: 'Food Types' },
  { title: 'Brunch', category: 'Food Types' },
  { title: 'Sandwiches', category: 'Food Types' },
  { title: 'Pasta', category: 'Food Types' },
  { title: 'Fried Chicken', category: 'Food Types' },
  { title: 'BBQ', category: 'Food Types' },
  { title: 'Bagel', category: 'Food Types' },
  { title: 'Bubble Tea', category: 'Food Types' },
  { title: 'Fries', category: 'Food Types' },
  { title: 'Dumplings', category: 'Food Types' },
  { title: 'Falafel', category: 'Food Types' },
  { title: 'Taco', category: 'Food Types' },
  { title: 'Poke', category: 'Food Types' },
  { title: 'Soup', category: 'Food Types' },
  { title: 'Pancakes', category: 'Food Types' },
  { title: 'Crépes', category: 'Food Types' },
  { title: 'Seafood', category: 'Food Types' },
  { title: 'Kebab', category: 'Food Types' },
  { title: 'Burritos', category: 'Food Types' },
  { title: 'Ice Cream', category: 'Food Types' },
  { title: 'Dessert', category: 'Food Types' },
  { title: 'Fingerfood', category: 'Food Types' },
  { title: 'Spicy', category: 'Food Types' },
  { title: 'Halal', category: 'Food Types' },
  { title: 'Salad', category: 'Food Types' },
  { title: 'Soup', category: 'Food Types' },
  { title: 'Juice', category: 'Food Types' },
  { title: 'Smoothie', category: 'Food Types' },
  { title: 'Bakery', category: 'Food Types' },
  { title: 'Cafe', category: 'Food Types' },
  { title: 'Burgers', category: 'Food Types' },
  { title: 'Meat', category: 'Food Types' },
  { title: 'Dim Sum', category: 'Food Types' }
];

const dietaryPreference = [
  { title: 'Vegetarian', category: 'Dietary Preference' },
  { title: 'Gluten-Free', category: 'Dietary Preference' },
  { title: 'Vegan', category: 'Dietary Preference' },
  { title: 'Lactose-Free', category: 'Dietary Preference' },
  { title: 'Keto', category: 'Dietary Preference' },
  { title: 'Low-Carb', category: 'Dietary Preference' },
  { title: 'Paleo', category: 'Dietary Preference' },
  { title: 'Pescetarian', category: 'Dietary Preference' },
  { title: 'Nut-Free', category: 'Dietary Preference' },
  { title: 'Diabetic', category: 'Dietary Preference' },
  { title: 'Low/No Sodium', category: 'Dietary Preference' }
];
