import React, { Fragment } from 'react';
import { Redirect, Route, Switch } from 'react-router-dom';
import Home from '../pages/Home';
import Profile from '../pages/Profile';
import Onboard from '../pages/Onboard';
import Login from '../pages/Login';
import Results from '../pages/Results';
import Loader from '../components/Loader';
import { withTracker } from 'meteor/react-meteor-data';
import Header from '../components/Header/Header';
import { TagCategories } from '../../api/tagCategories';
import { Tags } from '../../api/tags';
import { Accounts } from 'meteor/accounts-base';
import { withRouter } from 'react-router';
import MuiThemeProvider from '@material-ui/core/styles/MuiThemeProvider';

const isOnboarded = user => {
  return user.profile && user.profile.tags && user.profile.tags.length > 0;
};

const Layout = ({ loggedOut, currentUser, currentUserId }) => {
  if (!loggedOut) {
    if (!currentUser) {
      return <Loader inverted />;
    }
    return (
      <Fragment>
        <Header />
        {currentUser && isOnboarded(currentUser) ? (
          <Switch>
            <Route exact path="/home" component={Home} />
            <Route exact path="/profile" component={Profile} />
            <Route exact path="/onboard" component={Onboard} />
            <Route exact path="/results" component={Results} />
            <Redirect from="*" to="/home" />
          </Switch>
        ) : (
          <Switch>
            <Route exact path="/onboard" component={Onboard} />
            <Redirect from="*" to="/onboard" />
          </Switch>
        )}
      </Fragment>
    );
  } else {
    return (
      <Switch>
        <Route exact path="/welcome" component={Login} />
        <Redirect from="*" to="/welcome" />;
      </Switch>
    );
  }
};

// withRouter is required for the higher-order component
// generated by withTracker
export default withRouter(
  withTracker(() => {
    return {
      //the withtracker method lets us write a mongodb query and store the info in a prop called todos.
      //the Todos.find({}) is the mongodb query equivalent for SELECT * FROM Todos.
      currentUser: Meteor.user(),
      currentUserId: Meteor.userId(),
      loggedOut:
        !Meteor.user() &&
        !Meteor.loggingIn() &&
        Accounts.loginServicesConfigured()
    };
  })(Layout)
);
